spring.application.name=weather_api

# WHY: Base endpoint for Visual Crossing timeline API.
# WHAT: Used by WeatherService to build the final request URL.
weather.api.base-url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline

# WHY: The API key authorizes your app to call Visual Crossing.
weather.api.key=WAP6Y62M5SYUZYU5TRKRL2LJF
