spring.application.name=personal-blog
server.port=8080

# Filesystem directory where article JSON files will be stored.
blog.data.path=data/articles


blog.admin.username=admin
blog.admin.password=admin123
